modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Hunter19823/PresetJS/issues"
license = "MIT"

[[mods]]
modId = "presetjs"
version = "${version}"
displayName = "PresetJS"
authors = "ILIKEPIEFOO2"
logoFile="icon.png"
displayURL="https://github.com/Hunter19823/PresetJS"
description = '''
A KubeJS Addon for adding additional Presets
'''

[[dependencies.presetjs]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.presetjs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.presetjs]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
